### ISSUE TITLE
[1주차] 떡볶이 프로젝트 피드백

### ISSUE THREAD

**Issue by kkyu0718** [HappyNewYear23/TtheokBokkiZangBu#1]
정지연 코로나 극복 파이팅!

(좀 더 기발한 방법으로 돌아올게 원래 하려던게 이거긴 함..)

**Comment by stopkite** [comment]
감사합니다♥️ ~ 이틀 뒤에 격리 풀린다 ^^ ~!!!!!!!! 휴 ~!
