### ISSUE TITLE
이의 있습니다?!

### ISSUE THREAD

**Issue by kkyu0718** [HappyNewYear23/TtheokBokkiZangBu#3]
여기 왜 조용해요?
올려줘요

사실 심심해서 장난치려고 왔습니당 좋은 하루 되세요
@stopkite

**Comment by stopkite** [comment]
ㅋㅋㅋㅋㅋ 왜냐하면 카이트가 탈주했기 때문이죱 ㅠㅠ
좋은 하루 되십쇼 ^_^!!
